import { CatalogEntry } from './types';
import { EventType, PetSpecies } from './enums';

export const catalogSpecies: CatalogEntry<PetSpecies>[] = [
  { code: PetSpecies.DOG, label: 'Dog' },
  { code: PetSpecies.CAT, label: 'Cat' },
  { code: PetSpecies.BIRD, label: 'Bird' },
  { code: PetSpecies.REPTILE, label: 'Reptile' },
  { code: PetSpecies.SNAKE, label: 'Snake' },
  { code: PetSpecies.FROG, label: 'Frog' },
  { code: PetSpecies.TURTLE, label: 'Turtle' },
  { code: PetSpecies.OTHER, label: 'Other' },
];

export const catalogBreeds: Record<PetSpecies, CatalogEntry<string>[]> = {
  [PetSpecies.DOG]: [
    { code: 'AFGHAN_HOUND', label: 'Afghan Hound' },
    { code: 'AIREDALE_TERRIER', label: 'Airedale Terrier' },
    { code: 'AKITA', label: 'Akita' },
    { code: 'ALASKAN_MALAMUTE', label: 'Alaskan Malamute' },
    { code: 'AMERICAN_BULLDOG', label: 'American Bulldog' },
    { code: 'AMERICAN_ESKIMO_DOG', label: 'American Eskimo Dog' },
    { code: 'AMERICAN_FOXHOUND', label: 'American Foxhound' },
    { code: 'AMERICAN_PIT_BULL_TERRIER', label: 'American Pit Bull Terrier' },
    { code: 'AMERICAN_STAFFORDSHIRE_TERRIER', label: 'American Staffordshire Terrier' },
    { code: 'AUSTRALIAN_CATTLE_DOG', label: 'Australian Cattle Dog' },
    { code: 'AUSTRALIAN_SHEPHERD', label: 'Australian Shepherd' },
    { code: 'AUSTRALIAN_TERRIER', label: 'Australian Terrier' },
    { code: 'BASENJI', label: 'Basenji' },
    { code: 'BASSET_HOUND', label: 'Basset Hound' },
    { code: 'BEAGLE', label: 'Beagle' },
    { code: 'BELGIAN_MALINOIS', label: 'Belgian Malinois' },
    { code: 'BERNESE_MOUNTAIN_DOG', label: 'Bernese Mountain Dog' },
    { code: 'BICHON_FRISE', label: 'Bichon Frise' },
    { code: 'BORDER_COLLIE', label: 'Border Collie' },
    { code: 'BORDER_TERRIER', label: 'Border Terrier' },
    { code: 'BOSTON_TERRIER', label: 'Boston Terrier' },
    { code: 'BOXER', label: 'Boxer' },
    { code: 'BRITTANY', label: 'Brittany' },
    { code: 'BULL_TERRIER', label: 'Bull Terrier' },
    { code: 'BULLDOG', label: 'Bulldog' },
    { code: 'BULLMASTIFF', label: 'Bullmastiff' },
    { code: 'CAIRN_TERRIER', label: 'Cairn Terrier' },
    { code: 'CANE_CORSO', label: 'Cane Corso' },
    { code: 'CAVALIER_KING_CHARLES_SPANIEL', label: 'Cavalier King Charles Spaniel' },
    { code: 'CHIHUAHUA', label: 'Chihuahua' },
    { code: 'CHOW_CHOW', label: 'Chow Chow' },
    { code: 'COCKER_SPANIEL', label: 'Cocker Spaniel' },
    { code: 'COLLIE', label: 'Collie' },
    { code: 'DACHSHUND', label: 'Dachshund' },
    { code: 'DALMATIAN', label: 'Dalmatian' },
    { code: 'DOBERMAN_PINSCHER', label: 'Doberman Pinscher' },
    { code: 'ENGLISH_SETTER', label: 'English Setter' },
    { code: 'ENGLISH_SPRINGER_SPANIEL', label: 'English Springer Spaniel' },
    { code: 'FRENCH_BULLDOG', label: 'French Bulldog' },
    { code: 'GERMAN_SHEPHERD_DOG', label: 'German Shepherd Dog' },
    { code: 'GERMAN_SHORTHAIRED_POINTER', label: 'German Shorthaired Pointer' },
    { code: 'GOLDEN', label: 'Golden Retriever' },
    { code: 'GREAT_DANE', label: 'Great Dane' },
    { code: 'GREYHOUND', label: 'Greyhound' },
    { code: 'HAVANESE', label: 'Havanese' },
    { code: 'JACK_RUSSELL_TERRIER', label: 'Jack Russell Terrier' },
    { code: 'LABRADOR', label: 'Labrador Retriever' },
    { code: 'MALTESE', label: 'Maltese' },
    { code: 'MINIATURE_PINSCHER', label: 'Miniature Pinscher' },
    { code: 'MINIATURE_SCHNAUZER', label: 'Miniature Schnauzer' },
    { code: 'MIX', label: 'Mixed / Other' },
    { code: 'NEWFOUNDLAND', label: 'Newfoundland' },
    { code: 'POMERANIAN', label: 'Pomeranian' },
    { code: 'POODLE', label: 'Poodle' },
    { code: 'PUG', label: 'Pug' },
    { code: 'ROTTWEILER', label: 'Rottweiler' },
    { code: 'SAINT_BERNARD', label: 'Saint Bernard' },
    { code: 'SAMOYED', label: 'Samoyed' },
    { code: 'SHETLAND_SHEEPDOG', label: 'Shetland Sheepdog' },
    { code: 'SHIBA_INU', label: 'Shiba Inu' },
    { code: 'SHIH_TZU', label: 'Shih Tzu' },
    { code: 'SIBERIAN_HUSKY', label: 'Siberian Husky' },
    { code: 'STAFFORDSHIRE_BULL_TERRIER', label: 'Staffordshire Bull Terrier' },
    { code: 'WEIMARANER', label: 'Weimaraner' },
    { code: 'WEST_HIGHLAND_WHITE_TERRIER', label: 'West Highland White Terrier' },
    { code: 'YORKSHIRE_TERRIER', label: 'Yorkshire Terrier' }
  ],
  [PetSpecies.CAT]: [
    { code: 'SIAMESE', label: 'Siamese' },
    { code: 'PERSIAN', label: 'Persian' },
    { code: 'DOMESTIC_SHORTHAIR', label: 'Domestic Short hair' },
  ],
  [PetSpecies.BIRD]: [
    { code: 'PARROT', label: 'Parrot' },
    { code: 'CANARY', label: 'Canary' },
  ],
  [PetSpecies.REPTILE]: [
    { code: 'IGUANA', label: 'Iguana' },
    { code: 'TURTLE', label: 'Turtle' },
  ],
  [PetSpecies.SNAKE]: [],
  [PetSpecies.FROG]: [],
  [PetSpecies.TURTLE]: [],
  [PetSpecies.OTHER]: [{ code: 'OTHER', label: 'Other' }],
};

export const catalogEventTypes: CatalogEntry<EventType>[] = [
  { code: EventType.VACCINE, label: 'Vaccine' },
  { code: EventType.VET_VISIT, label: 'Vet visit' },
  { code: EventType.MEDICATION, label: 'Medication' },
  { code: EventType.WEIGHT, label: 'Weight' },
  { code: EventType.GROOMING, label: 'Grooming' },
  { code: EventType.INCIDENT, label: 'Incident' },
  { code: EventType.WALK, label: 'Walk' },
  { code: EventType.FEEDING, label: 'Feeding' },
  { code: EventType.OTHER, label: 'Other' },
];

export interface VaccineDefinition extends CatalogEntry<string> {
  recommendedIntervalDays?: number;
}

export const catalogVaccines: VaccineDefinition[] = [
  { code: 'RABIES', label: 'Rabies', recommendedIntervalDays: 365 },
  { code: 'DISTEMPER', label: 'Distemper (DHPP)', recommendedIntervalDays: 365 },
  { code: 'BORDETELLA', label: 'Bordetella', recommendedIntervalDays: 180 },
  { code: 'FVRCP', label: 'FVRCP (cats)', recommendedIntervalDays: 365 },
  { code: 'OTHER', label: 'Other / custom' },
];
