#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running Nx lint/test on affected projects..."
npx nx affected --target=lint --parallel=3 --base=origin/main --head=HEAD || exit 1
npx nx affected --target=test --parallel=1 --runInBand --base=origin/main --head=HEAD --skip-nx-cache || exit 1
