name: Snyk Security Scan

on:
  push:
    branches:
      - develop
  pull_request:
  schedule:
    - cron: '0 10 * * 1'

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Snyk test (all projects)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >-
            --all-projects
            --detection-depth=4
            --severity-threshold=high
            --sarif-file-output=snyk.sarif

#      - name: Upload SARIF to GitHub
#          if: always()
#        uses: github/codeql-action/upload-sarif@v4
#        with:
#          sarif_file: snyk.sarif
